package jvm_memory;

import org.junit.Test;

import java.io.*;
import java.util.Date;

public class Demo1 {

    @Test
    public void f1(){

        //系统运行占用的deep内存 17,007,280
        //permgen内存10,059,712

        for (double i = 0; i<8800000000d; i++){

            String a = new String(i+"qweasqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxdzxcqweasqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxdzxcqweasqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxdzxcqweasqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxdzxcqweasqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxdzxcqweasqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxdzxc");
//            String intern = a.intern();
        }

    }

    @Test
    public void f2(){

        try {

            FileReader fileReader = new FileReader("Y:\\demo.wmv");
            BufferedReader bufferedReader = new BufferedReader(fileReader);

            StringBuffer stringBuffer = new StringBuffer();
            String line = null;

            while ((line=bufferedReader.readLine())!=null){
                stringBuffer.append(line);
            }

            String s = stringBuffer.toString();
            String intern = s.intern();
            System.out.println(s.length());

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }


    }

}
