package jvm_memory;

import org.junit.Test;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;

public class Demo1 {

    @Test
    public void f1(){

        //系统运行占用的deep内存 22,628,272

        //permgen内存8,769,416


        for (double i = 0; i<8800000000d; i++){

            String a = i+"qweasqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxdzxcqweasqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxdzxcqweasqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxdzxcqweasqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxdzxcqweasqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxdzxcqweasqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxqweasdzxdzxc";
            String intern = a.intern();
        }

    }

    @Test
    public void f2(){
        try {

            FileReader fileReader = new FileReader("Y:\\demo.wmv");
            BufferedReader bufferedReader = new BufferedReader(fileReader);

            StringBuffer stringBuffer = new StringBuffer();
            String line = null;

            while ((line=bufferedReader.readLine())!=null){
                stringBuffer.append(line);
            }

            String s = stringBuffer.toString();
            String intern = s.intern();
            System.out.println(s.length());

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

}
